lsa_test_stand/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin

admin.autodiscover()

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include("web_site.urls", namespace="web_site")),
]

if settings.DEBUG:
    urlpatterns.extend([
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    ])

web_site/urls.py
from django.conf.urls import url
from web_site import views

urlpatterns = [
    url(r'^$', views.SearchView.as_view(), name="search"),
    url(r'^save/$', views.SaveAccessorMarks.as_view(), name="save"),
    url(r'^documents/(?P<pk>\d+)/$', views.DocumentView.as_view(), name="document"),
    url(r'results/$', views.ResultPage.as_view(), name="result")
]

web_site/models.py
import math

from ckeditor.fields import RichTextField
from django.db import models


class DocumentGroup(models.Model):
    title = models.CharField(max_length=128)

    def __str__(self):
        return str(self.title)


class Document(models.Model):
    title = models.CharField(max_length=250)
    group = models.ForeignKey(DocumentGroup, related_name='documents', blank=True, null=True)
    content = RichTextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.title)


def get_bool_map(rates, is_strong=False):
    """ Array of boolean query map. True if answer is relevant and False other way """

    threshold = SearchResult.RELEVANT_PLUS if is_strong else SearchResult.RELEVANT_MINUS
    return [True if r >= threshold else False for r in rates]


def precision_at_k(map, k):
    """ Precision@K """

    assert (k > 0)
    map_slice = map[:k]
    return sum(map_slice) / k


def avg_precision(map):
    """ Average Precision metric (AP) """

    prec = []
    for index, rate in enumerate(map):
        if rate:
            prec.append(precision_at_k(map, index + 1))
    return sum(prec) / (len(prec) or 1)


def dcg(rates):
    """ DCG metric """

    values = [(2 ** r - 1) / (math.log2(index + 2)) for index, r in enumerate(rates)]
    return sum(values)


def reciprocal_rank(map):
    """ Reciprocal rank metric """

    for index, item in enumerate(map):
        if item is True:
            return 1 / (index + 1)


class SearchQuery(models.Model):
    query = models.CharField(max_length=128)
    ip = models.GenericIPAddressField()
    created_at = models.DateTimeField(auto_now_add=True)

    # precision
    lsa_weak_precision = models.FloatField(blank=True, null=True)
    lsa_strong_precision = models.FloatField(blank=True, null=True)
    ideal_weak_precision = models.FloatField(blank=True, null=True)
    ideal_strong_precision = models.FloatField(blank=True, null=True)

    # avg precision
    lsa_weak_avg_prec = models.FloatField(blank=True, null=True)
    lsa_strong_avg_prec = models.FloatField(blank=True, null=True)
    ideal_weak_avg_prec = models.FloatField(blank=True, null=True)
    ideal_strong_avg_prec = models.FloatField(blank=True, null=True)

    # reciprocal rank
    lsa_weak_reciprocal_rank = models.FloatField(blank=True, null=True)
    lsa_strong_reciprocal_rank = models.FloatField(blank=True, null=True)
    ideal_weak_reciprocal_rank = models.FloatField(blank=True, null=True)
    ideal_strong_reciprocal_rank = models.FloatField(blank=True, null=True)

    # discounted cumulative gain
    lsa_ndcg = models.FloatField(blank=True, null=True)
    ideal_ndcg = models.FloatField(blank=True, null=True)

    def get_rates(self, engine):
        return self.searchresult_set.filter(engine=engine).order_by('position').values_list('relevance', flat=True)

    def calc_metrics(self):
        lsa_rates = self.get_rates(SearchResult.LSA)
        ideal_rates = self.get_rates(SearchResult.SPHINX)

        weak_lsa_map = get_bool_map(lsa_rates)
        strong_lsa_map = get_bool_map(lsa_rates, is_strong=True)
        weak_ideal_map = get_bool_map(ideal_rates)
        strong_ideal_map = get_bool_map(ideal_rates, is_strong=True)

        self.lsa_weak_precision = sum(weak_lsa_map) / (len(weak_lsa_map) or 1)
        self.lsa_strong_precision = sum(strong_lsa_map) / (len(strong_lsa_map) or 1)
        self.ideal_weak_precision = sum(weak_ideal_map) / (len(weak_ideal_map) or 1)
        self.ideal_strong_precision = sum(strong_ideal_map) / (len(strong_ideal_map) or 1)

        self.lsa_weak_avg_prec = avg_precision(weak_lsa_map)
        self.lsa_strong_avg_prec = avg_precision(strong_lsa_map)
        self.ideal_weak_avg_prec = avg_precision(weak_ideal_map)
        self.ideal_strong_avg_prec = avg_precision(strong_ideal_map)

        self.lsa_ndcg = dcg(lsa_rates) / (dcg(sorted(lsa_rates, reverse=True)) or 1)
        self.ideal_ndcg = dcg(ideal_rates) / (dcg(sorted(ideal_rates, reverse=True)) or 1)

        self.lsa_weak_reciprocal_rank = reciprocal_rank(weak_lsa_map)
        self.lsa_strong_reciprocal_rank = reciprocal_rank(strong_lsa_map)
        self.ideal_weak_reciprocal_rank = reciprocal_rank(weak_ideal_map)
        self.ideal_strong_reciprocal_rank = reciprocal_rank(strong_ideal_map)

        self.save()

    def __str__(self):
        return str(self.query)


class SearchResult(models.Model):
    LSA, SPHINX = 1, 2
    ENGINES = (
        (LSA, "LSA"),
        (SPHINX, "Sphinx")
    )

    NOT_RELEVANT, RELEVANT_MINUS, RELEVANT_PLUS, RELEVANT = 0, 1, 2, 3
    RELEVANCE_CHOICES = (
        (NOT_RELEVANT, "Не релевантный"),
        (RELEVANT_MINUS, "Немного соответсвует запросу"),
        (RELEVANT_PLUS, "По большей степени соответствует запросу"),
        (RELEVANT, "Совершенно релевантный"),
    )

    document = models.ForeignKey(Document)
    search_query = models.ForeignKey(SearchQuery)
    engine = models.SmallIntegerField(choices=ENGINES)
    relevance = models.SmallIntegerField(choices=RELEVANCE_CHOICES)
    position = models.SmallIntegerField()

    def __str__(self):
        return str(self.relevance)

web_site/views.py
import json

import operator
import random
import sphinxapi
from django.conf import settings
from django.db import transaction
from django.db.models import Avg
from django.http import HttpResponse
from django.views import generic
from lsa.search.machine import SearchMachine
from web_site import models


class SearchView(generic.TemplateView):
    template_name = "web_site/search.html"

    def get_context_data(self, **kwargs):
        cd = super(SearchView, self).get_context_data(**kwargs)

        query = self.request.GET.get('q', '')
        cd['query'] = query
        if query:
            semantic_results = self.search_by_lsa(query)
            sphinx_results = self.search_by_sphinx(query)
            results = [{"records": semantic_results, "engine": models.SearchResult.LSA},
                       {"records": sphinx_results, "engine": models.SearchResult.SPHINX}]
            random.shuffle(results)
            cd["results"] = results
        cd["relevance_levels"] = models.SearchResult.RELEVANCE_CHOICES
        return cd

    def sort_by_given_order(self, values, order, getter):
        results = []
        ignored = []
        for pos_value in order:
            for v in values:
                if v not in ignored and getter(v) == pos_value:
                    results.append(v)
                    ignored.append(v)
                    break
        return results

    def get_documents(self, pks):
        documents = models.Document.objects.filter(pk__in=pks)
        return self.sort_by_given_order(documents, pks, operator.attrgetter('id'))

    def search_by_lsa(self, query):
        sm = SearchMachine(**settings.INDEX_SETTINGS)
        search_results = sm.search(query, with_distances=True, limit=10)
        pks = []
        if search_results:
            pks = [r[0] for r in search_results]
        print(len(pks), "LSA")
        return self.get_documents(pks)

    def search_by_sphinx(self, query):
        client = sphinxapi.SphinxClient()
        client.SetServer(settings.SPHINX_HOST, settings.SPHINX_PORT)
        response = client.Query(query, index=settings.SPHINX_INDEX_NAME)
        pks = []
        if response:
            matches = response['matches']
            pks = [m['id'] for m in matches]
        print(len(pks), "Sphinx")
        return self.get_documents(pks)


class SaveAccessorMarks(generic.View):
    @transaction.atomic
    def post(self, request, *args, **kwargs):
        data = request.POST
        marks = data.get("marks")
        marks = json.loads(marks)
        new_query = models.SearchQuery.objects.create(query=data.get("query"), ip=request.META.get('REMOTE_ADDR'))
        new_results = []
        for mark in marks:
            new_r = models.SearchResult(search_query=new_query, document_id=int(mark['document']),
                                        engine=int(mark['engine']), relevance=int(mark['relevance']),
                                        position=int(mark['position']))
            new_results.append(new_r)
        models.SearchResult.objects.bulk_create(new_results)
        return HttpResponse()


class DocumentView(generic.DetailView):
    template_name = 'web_site/document.html'
    context_object_name = "document"
    model = models.Document


class ResultPage(generic.TemplateView):
    template_name = 'web_site/results.html'

    def get_context_data(self, **kwargs):
        cd = super(ResultPage, self).get_context_data(**kwargs)
        queries = models.SearchQuery.objects.all()

        # precision
        cd['avg_lsa_weak_precision'] = queries.aggregate(v=Avg('lsa_weak_precision'))['v']
        cd['avg_lsa_strong_precision'] = queries.aggregate(v=Avg('lsa_strong_precision'))['v']
        cd['avg_ideal_weak_precision'] = queries.aggregate(v=Avg('ideal_weak_precision'))['v']
        cd['avg_ideal_strong_precision'] = queries.aggregate(v=Avg('ideal_strong_precision'))['v']
        avg_week_prec_delta = abs(cd["avg_lsa_weak_precision"] - cd["avg_ideal_weak_precision"])
        cd['avg_week_prec_delta'] = avg_week_prec_delta
        cd['avg_week_prec_delta_percent'] = avg_week_prec_delta / cd["avg_ideal_weak_precision"] * 100
        avg_strong_prec_delta = abs(cd['avg_lsa_strong_precision'] - cd['avg_ideal_strong_precision'])
        cd['avg_strong_prec_delta'] = avg_strong_prec_delta
        cd['avg_strong_prec_delta_percent'] = avg_strong_prec_delta / cd['avg_ideal_strong_precision'] * 100

        # MAP
        cd['lsa_weak_map'] = queries.aggregate(v=Avg('lsa_weak_avg_prec'))['v']
        cd['lsa_strong_map'] = queries.aggregate(v=Avg('lsa_strong_avg_prec'))['v']
        cd['ideal_weak_map'] = queries.aggregate(v=Avg('ideal_weak_avg_prec'))['v']
        cd['ideal_strong_map'] = queries.aggregate(v=Avg('ideal_strong_avg_prec'))['v']
        lsa_weak_map_delta = abs(cd['lsa_weak_map'] - cd['ideal_weak_map'])
        cd['lsa_weak_map_delta'] = lsa_weak_map_delta
        cd['lsa_weak_map_delta_percent'] = lsa_weak_map_delta / cd['ideal_weak_map'] * 100
        lsa_strong_map_delta = abs(cd['lsa_strong_map'] - cd['ideal_strong_map'])
        cd['lsa_strong_map_delta'] = lsa_strong_map_delta
        cd['lsa_strong_map_delta_percent'] = lsa_strong_map_delta / cd['ideal_strong_map'] * 100

        # NDCG
        cd['avg_lsa_ndcg'] = queries.aggregate(v=Avg("lsa_ndcg"))['v']
        cd['avg_ideal_ndcg'] = queries.aggregate(v=Avg("ideal_ndcg"))['v']
        avg_ndcg_delta = abs(cd['avg_lsa_ndcg'] - cd['avg_ideal_ndcg'])
        cd['avg_ndcg_delta'] = avg_ndcg_delta
        cd['avg_ndcg_delta_percent'] = avg_ndcg_delta / cd['avg_ideal_ndcg'] * 100

        # MRR
        cd['avg_lsa_weak_mrr'] = queries.aggregate(v=Avg("lsa_weak_reciprocal_rank"))['v']
        cd['avg_lsa_strong_mrr'] = queries.aggregate(v=Avg("lsa_strong_reciprocal_rank"))['v']
        cd['avg_ideal_weak_mrr'] = queries.aggregate(v=Avg("ideal_weak_reciprocal_rank"))['v']
        cd['avg_ideal_strong_mrr'] = queries.aggregate(v=Avg("ideal_strong_reciprocal_rank"))['v']
        lsa_weak_mrr_delta = abs(cd['avg_lsa_weak_mrr'] - cd['avg_ideal_weak_mrr'])
        cd['lsa_weak_mrr_delta'] = lsa_weak_mrr_delta
        cd['lsa_weak_mrr_delta_percent'] = lsa_weak_mrr_delta / cd['avg_ideal_weak_mrr'] * 100
        lsa_strong_mrr_delta = abs(cd['avg_lsa_strong_mrr'] - cd['avg_ideal_strong_mrr'])
        cd['lsa_strong_mrr_delta'] = lsa_strong_mrr_delta
        cd['lsa_strong_mrr_delta_percent'] = lsa_strong_mrr_delta / cd['avg_ideal_strong_mrr'] * 100

        return cd

templates/web_site/document.html
{% extends "base.html" %}

{% block content %}
    <div class="row">
        <div class="col-lg-12">
            <h3>{{ document.title }}</h3>

            <p>{{ document.content|safe }}</p>
        </div>
    </div>
{% endblock %}

templates/web_site/results.html
{% extends "base.html" %}

{% block content %}
    <div class="row">

        <h3>Точность (Precision)</h3>

        <table class="table">
            <thead>
            <tr>
                <th>Средняя слаборелевантная точность (LSA)</th>
                <th>Средняя слаборелевантная точность (Sphinx)</th>
                <th>Среднее отклонение слаборелевантной точности, абс</th>
                <th>Среднее отклонение слаборелевантной точности, %</th>

                <th>Средняя сильнорелевантная точность (LSA)</th>
                <th>Средняя сильнорелевантная точность (Sphinx)</th>
                <th>Среднее отклонение сильнорелевантной точности, абс</th>
                <th>Среднее отклонение сильнорелевантной точности, %</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>{{ avg_lsa_weak_precision|floatformat:2 }}</td>
                <td>{{ avg_ideal_weak_precision|floatformat:2 }}</td>
                <td>{{ avg_week_prec_delta|floatformat:2 }}</td>
                <td>{{ avg_week_prec_delta_percent|floatformat:2 }}</td>
                <td>{{ avg_lsa_strong_precision|floatformat:2 }}</td>
                <td>{{ avg_ideal_strong_precision|floatformat:2 }}</td>
                <td>{{ avg_strong_prec_delta|floatformat:2 }}</td>
                <td>{{ avg_strong_prec_delta_percent|floatformat:2 }}</td>
            </tr>
            </tbody>
        </table>

        <h3>Усредненная средняя точность (Mean average precision)</h3>

        <table class="table">
            <thead>
            <tr>
                <th>Средняя слаборелевантная MAP (LSA)</th>
                <th>Средняя слаборелевантная MAP (Sphinx)</th>
                <th>Среднее отклонение слаборелевантной MAP, абс</th>
                <th>Среднее отклонение слаборелевантной MAP, %</th>

                <th>Средняя сильнорелевантная MAP (LSA)</th>
                <th>Средняя сильнорелевантная MAP (Sphinx)</th>
                <th>Среднее отклонение сильнорелевантной MAP, абс</th>
                <th>Среднее отклонение сильнорелевантной MAP, %</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>{{ lsa_weak_map|floatformat:2 }}</td>
                <td>{{ ideal_weak_map|floatformat:2 }}</td>
                <td>{{ lsa_weak_map_delta|floatformat:2 }}</td>
                <td>{{ lsa_weak_map_delta_percent|floatformat:2 }}</td>
                <td>{{ lsa_strong_map|floatformat:2 }}</td>
                <td>{{ ideal_strong_map|floatformat:2 }}</td>
                <td>{{ lsa_strong_map_delta|floatformat:2 }}</td>
                <td>{{ lsa_strong_map_delta_percent|floatformat:2 }}</td>
            </tr>
            </tbody>
        </table>

        <h3>NDCG (Discounted Cumulative Gain)</h3>

        <table class="table">
            <thead>
            <tr>
                <th>Средняя NDCG (LSA)</th>
                <th>Средняя NDCG (Sphinx)</th>
                <th>Среднее отклонение NDCG, абс</th>
                <th>Среднее отклонение NDCG, %</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>{{ avg_lsa_ndcg|floatformat:2 }}</td>
                <td>{{ avg_ideal_ndcg|floatformat:2 }}</td>
                <td>{{ avg_ndcg_delta|floatformat:2 }}</td>
                <td>{{ avg_ndcg_delta_percent|floatformat:2 }}</td>
            </tr>
            </tbody>
        </table>


        <h3>Усредненная ценность ответа (Mean Reciprocal Rank)</h3>

        <table class="table">
            <thead>
            <tr>
                <th>Средняя слаборелевантная MRR (LSA)</th>
                <th>Средняя слаборелевантная MRR (Sphinx)</th>
                <th>Среднее отклонение слаборелевантной MRR, абс</th>
                <th>Среднее отклонение слаборелевантной MRR, %</th>

                <th>Средняя сильнорелевантная MRR (LSA)</th>
                <th>Средняя сильнорелевантная MRR (Sphinx)</th>
                <th>Среднее отклонение сильнорелевантной MRR, абс</th>
                <th>Среднее отклонение сильнорелевантной MRR, %</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>{{ avg_lsa_weak_mrr|floatformat:2 }}</td>
                <td>{{ avg_ideal_weak_mrr|floatformat:2 }}</td>
                <td>{{ lsa_weak_mrr_delta|floatformat:2 }}</td>
                <td>{{ lsa_weak_mrr_delta_percent|floatformat:2 }}</td>
                <td>{{ avg_lsa_strong_mrr|floatformat:2 }}</td>
                <td>{{ avg_ideal_strong_mrr|floatformat:2 }}</td>
                <td>{{ lsa_strong_mrr_delta|floatformat:2 }}</td>
                <td>{{ lsa_strong_mrr_delta_percent|floatformat:2 }}</td>
            </tr>
            </tbody>
        </table>
    </div>
{% endblock %}

templates/web_site/search.html
{% extends "base.html" %}

{% block content %}
    <div class="row">

        <div class="spoiler">
            <div class="spoiler-trigger"><em>Интструкция-описание</em></div>
            <div class="spoiler-body collapse">
                <p class="lead">
                    Данный сайт представляет собой тестовый стенд одной магистерской работы. На данный момент нужно
                    сравнить
                    собственное поделие с эталоной машиной полнотестового поиска, в качестве которой выступает Sphinx
                    search
                    engine. На каждый поисковый запрос будут отображены две колонки результатов: одна - поисковая
                    выборка от
                    сфинкса,
                    вторая - от кастомного кода. Колонки иногда меняются местами, событие смены - случайное.
                </p>

                <p class="lead">
                    Поиск - сфера сложная и для подсчета метрик качетсва необходимы экспертные оценки релевантности
                    поисковой выдачи. Сегодня вы среди экспертов!
                    Каждый результат обеих выдач необходимо оченить по 4х-бальной шкале. После оценки необходимо
                    отправить результаты в базу, нажав "Сохранить результаты"
                </p>
                <ul class="lead">
                    <li>
                        не релевантный (документ явно
                        лишний для запроса)
                    </li>
                    <li>
                        немного соответствует
                        запросу (в тексте есть нужные упоминания, но в целом он про другое)
                    </li>
                    <li>
                        по большей степени
                        соответсвует
                        запросу (предмет запроса среди основных тем документа)
                    </li>
                    <li>
                        совершенно релевантный
                    </li>
                </ul>
            </div>
        </div>


        <h1>Поиск по документам</h1>

        <form method="get" action="{% url "web_site:search" %}">
            <div class="form-group">
                <input class="form-control" name="q" id="q" value="{{ query }}" type="text"
                       placeholder="про космос, программирование или старые свитки">

            </div>
            <button type="submit" class="btn btn-default">Начать поиск</button>
            {% if query %}
                <button type="button" class="btn btn-default" id="save">Сохранить результаты
                </button>
            {% endif %}
        </form>
        {% csrf_token %}
    </div>

    {% if query %}
        <hr/>

        <div class="row">
            <div class="col-lg-6">
                {% with records=results.0.records engine=results.0.engine %}
                    {% include "web_site/includes/search-item.html" %}
                {% endwith %}
            </div>
            <div class="col-lg-6">
                {% with records=results.1.records engine=results.1.engine %}
                    {% include "web_site/includes/search-item.html" %}
                {% endwith %}
            </div>
        </div>
    {% endif %}

    <div class="modal fade bs-example-modal-sm" id="incomplete-modal" tabindex="-1" role="dialog"
         aria-labelledby="mySmallModalLabel">
        <div class="modal-dialog modal-sm">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Оповещение</h4>
                </div>
                <div class="modal-body">
                    Не всем результатам проставлена релевантность
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade bs-example-modal-sm" id="success-modal" tabindex="-1" role="dialog"
         aria-labelledby="mySmallModalLabel2">
        <div class="modal-dialog modal-sm">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="mySmallModalLabel2">Оповещение</h4>
                </div>
                <div class="modal-body">
                    Спасибо! а теперь еще один поисковый запрос ;)
                </div>
            </div>
        </div>
    </div>

    <script>
        $(document).ready(function () {
            $(".spoiler-trigger").on('click', function (e) {
                e.preventDefault();
                $(this).parent().children('.spoiler-body').collapse('toggle')
            });


            var saveButton = $("#save");
            saveButton.click(function () {
                var results = $('select[data-role="result"]');
                var marks = [];
                var marked = 0;
                results.each(function (i) {
                    var res = $(this);
                    var value = res.val();
                    if (value) {
                        marked++
                    }
                    marks.push({
                        "engine": res.data("engine"),
                        "document": res.data("document"),
                        "relevance": value,
                        "position": res.data("position")
                    })
                });
                if (marked != marks.length) {
                    $("#incomplete-modal").modal()
                } else {

                    $.ajax({
                        url: {% url "web_site:save" %},
                        type: "POST",
                        data: {
                            "query": $("#q").val(),
                            "marks": JSON.stringify(marks),
                            "csrfmiddlewaretoken": $('input[name="csrfmiddlewaretoken"]').val()
                        },
                        success: function () {
                            $("#success-modal").modal();
                            window.location.search = '';
                        }

                    })
                }
            })
        })
    </script>
{% endblock %}